version: 2
updates:
  - package-ecosystem: "poetry"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    version: "patch"
    commit-message:
      prefix: "chore(deps): update"
      include: "dependencies"
    automerged: false
    labels:
      - "dependencies"
    target-branch: "main"
