[pyplater.scripts]
script = "python ./script/main.py"
test = "python -m unittest discover test"
lint = "flake8"
format = "black . -v"
install = "pip install -r requirements.txt"
install-dev = "pip install -r requirements.dev.txt"
create-venv = "python -m venv .venv"
activate-venv = "source .venv/Scripts/activate"