name: Update Badges

on:
  workflow_run:
    workflows: ["ci"]
    types:
      - completed

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - name: in Progress
        run: echo "Hold up im working on it"
      # - name: Check coverage percentage
      #   id: coverage
      #   run: echo "::set-output name=coverage::$(awk '/^TOTAL/ {print substr($4, 1, length($4)-1)}' .coverage/index.html)"

      # - name: Update badge
      #   run: |
      #     echo "CODE_COVERAGE=${{ steps.coverage.outputs.coverage }}" >> $GITHUB_ENV
      #     echo "Code coverage: ${{ steps.coverage.outputs.coverage }}%"
