name: Update Badges

on:
  push:
    branches: [main]
  workflow_run:
    workflows: ["ci"]
    types:
      - completed

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - name: Check CI workflow status
        id: check_ci
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const runs = await github.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'ci.yml',
              branch: 'main',
              status: 'completed',
              per_page: 1
            });
            core.setOutput('ci_completed', runs.data.total_count === 1 && runs.data.workflow_runs[0].conclusion === 'success');
      - name: in Progress
        run: echo "Hold up im working on it"
      # - name: Check coverage percentage
      #   id: coverage
      #   run: echo "::set-output name=coverage::$(awk '/^TOTAL/ {print substr($4, 1, length($4)-1)}' .coverage/index.html)"

      # - name: Update badge
      #   run: |
      #     echo "CODE_COVERAGE=${{ steps.coverage.outputs.coverage }}" >> $GITHUB_ENV
      #     echo "Code coverage: ${{ steps.coverage.outputs.coverage }}%"
